# Generated by Django 2.2.3 on 2021-06-02 12:08

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_accessability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='accessability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(upload_to='Files', validators=[blog.models.file_size]),
        ),
    ]
